# Generated by Django 5.0.6 on 2024-11-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(default='game_account', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='socialSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='stockQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=30)),
                ('text', models.CharField(default='Some description stuff.', max_length=200)),
                ('new_stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.newstocks')),
            ],
        ),
    ]
